### ISSUE TITLE
Provide seed data for Agents

### ISSUE THREAD

**Issue by atbaker** [TwilioDevEd/ivr-recording-laravel#4]
After setting up the app, I could get to the `ExtensionController` logic, but when I chose an extension it would redirect me back to the main menu instead of connecting me to the agent.

I think it's because the `$planetExtensions` are hard-coded, but since this version of the tutorial relies on an `Agent` model database, we need to have that data pre-populated.

Here's what that seed file looks like in the Rails app:
https://github.com/TwilioDevEd/ivr-recording-rails/blob/master/db/seeds.rb

And here's how the controller makes it dynamic:
https://github.com/TwilioDevEd/ivr-recording-rails/blob/master/app/controllers/twilio_controller.rb#L149-L158

Maybe you already have seed data, but I just missed it. In which case, add a note about how to load that data in the README.

**Comment by jsantos17** [comment]
Addressed by 879aa4c07ae5709e231b17af11d7a088ef6b2add

I used the same numbers as the Rails app.

**Comment by atbaker** [comment]
This is now working - thanks! Unfortunately I ran into another bug a little further down the line with #5
