### ISSUE TITLE
500 error when trying to view recordings for an agent

### ISSUE THREAD

**Issue by atbaker** [TwilioDevEd/ivr-recording-laravel#5]
Thanks to the fix for #4, I can now leave voicemails. But I can't view my recordings as an agent.

For example, going to http://localhost:8000/recording?agentNumber=+15552483591 produces a 500 error. It looks like the E.164 formatted phone number query parameter might be getting messed up in the controller before it can be used to query the database.

**Comment by jsantos17** [comment]
You might need to escape the `+` there. The browser might be interpreting it as a space.

**Comment by atbaker** [comment]
You're right - this URL works: http://localhost:8000/recording?agentNumber=%2b15552483591

I'm worried, though, that a developer checking out our app for the first time might have the same problem. Can you either:

1. Alter the URL and controller so it's no longer necessary to include the `+` in the URL, or
1. Add links to each Agent's recordings from the home page

**Comment by jsantos17** [comment]
I implemented a quickfix in 7530b2973900bb40c86a6da59799010402598317. I'm slightly concerned that we're no longer using E.164 format anymore.

**Comment by atbaker** [comment]
Agreed - it's not ideal, but thanks for fixing it.
